import { BrowserRouter } from "react-router-dom";
import { MockedProvider } from "@apollo/client/testing";
import { GET_REVIEW } from "../Queries";
import ReviewDetails from "../../pages/ReviewDetails";

// Mock data for 5 reviews
const { id } = 5;
const mocks = [
  {
    request: {
      query: GET_REVIEW,
      variables: { id: id },
    },
    result: {
      data: {
        review: {
          data: {
            id: "5",
            attributes: {
              Title: "Rollercoaster Tycoon 2",
              Body: "You can drown the bad people if you like.\n\nA Hurricane battlecruiser and Buzzard are on d-scan in C2a, along with a tower, but I see no wrecks and no anomalies. Oh yeah, just every damn expansion at this point, that’s all. That feeling will pass, but then I'll say in all honesty that I don't know what other MMO I'd likely play any time soon, after GW2....what is there, anyway? And I’m still playing EQ2 here and there and looking forward to Vanguard’s f2p move set for some time in August. The first one will come out this December and the second a year after, in 2013.\n\nThe community could regulate itself by ostrasizing harmful elements such as ninjas, slackers and jerks. We could consider GW2 and Pandaria's approaches as an attempt to fight the jerkish community, but I actually see them as a way of rose-tinting the community. Another great update for MMO fans, this time bringing mounted combat to Lord of the Rings Online. Should be fun. Over the weekend I managed to finish up the new quests from the Qeynos Rises update, in EQ2. Don’t capture the South GY unless you know exactly what you are doing. EQ2 players are a tolerably cheerful bunch as MMO players go (raiders excepted) and they do like a party.\n\nOh and soon after that, I managed to get Zen Master Archaeologist. Least time spent in group while leveling: SWTOR and STO - as far as I can recall, none of my capped characters in either game has ever joined a group for any reason. Now, there’s a very lore-centric reason that Turbine chose to exclude female dwarves, and it’s not that they don’t exist. This probably is the most 'normal' character of the three. SWTOR now has three raids: Eternity Vault, Karagga's Palace, and Explosive Conflict. In this case, it was a weekend of playing nothing but RIFT.\n\nIt struck me the other day, that the idea of not getting her to the new level cap just feels…wrong. That meant ditching my Sentinel soul, scaling back on my Shaman talents, and weaving in a very strong dose of Justicar. Of course, I learned a couple of days before BWE3 that Jennifer Hale is voicing the sylvari female — that’s Commander Shepard from the Mass Effect trilogy. Just to remind me that an MMO isn't all sweetness and light, I encountered an Imperial L50 on Tatooine the other day. Out of all the tests over the last few months that was the one where, finally, everything came together, coalesced into a feeling of understanding that allowed me to really, truly, enjoy the game.\n\nMost likely this means that you received a fraudulent code from a third-party seller. I’ve previously talked about the true dynamic nature of WH space in EVE, and I want to use last weekends Op as a backdrop to sum that thought up and perhaps add some clarity to it as well. When we finally managed to be online at the same time and chat with each other, he asked me one question: “How do you get new skills in this game?” Hard Mode drops a specific tier of gear. Hard Mode flashpoints drop Tionese, Eternity Vault drops Columni, Karagga's Palace drops Rakata, and Explosive Conflict drops Black Hole.\n\nGenerated by MMO Ipsum Generator.",
              Rating: 9,
            },
          },
        },
      },
    },
  },
];
//Mocked ApolloProvider
export const MockReview = () => {
  return (
    <MockedProvider mocks={mocks}>
      <BrowserRouter>
        <ReviewDetails />
      </BrowserRouter>
    </MockedProvider>
  );
};
